version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: fiap
      MYSQL_DATABASE: contatos
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: