name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose.yml up -d

    - name: Wait for MySQL to be ready
      run: docker-compose exec -T mysql sh -c 'until mysqladmin ping --silent; do echo "waiting for mysql"; sleep 2; done'    

    - name: Run Unit Tests
      run: dotnet test CadastroContatosTestesUnitarios --no-build --verbosity normal
      
    - name: Run SQL command to get system date
      run: mysql -h localhost -u fiap -pfiap -D contatos -e "SELECT NOW();"

    #- name: Run Integration Tests      
    #  run: ConnectionStrings__Contatos="Server=localhost;Database=contatos;User=fiap;Password=fiap;" dotnet test CadastroContatosTests --no-build --verbosity normal

    - name: Shut down Docker Compose
      run: docker-compose down
